### ISSUE TITLE
Some links / formatting from md not rendered in HTML?

### ISSUE THREAD

**Issue by fabian-s** [teaching-data-science/intro2ml#4]
e.g. in chapters/contents.md
```
ractical assignments, the latter in **`R`** (mostly with 
[`mlr3`](https://mlr3.mlr-org.com/)).
``` 
gets rendered as 
![image](https://user-images.githubusercontent.com/998541/85550518-5685b280-b621-11ea-9900-475d05910552.png)
(R not monospace, mlr3 link not clickable)

(Links are rendered correctly elsewhere, so not a general problem...)

**Comment by OmidCharrakh** [comment]
I corrected these links, but please let me know if there are still some other problematic links.
