### ISSUE TITLE
possible to have multiple levels of chapters?

### ISSUE THREAD

**Issue by fabian-s** [teaching-data-science/intro2ml#5]
i.e., have chapters
1 Intro  
2 Regression
....

that lead to dedicated sub-pages for the different x.1 , x.2 sub-chapters?

Would be nicer, I think, so the landing page is a little less overwhelming and more orgnaized -- e.g. does not seem well-designed to have the same level of heading for a collection of ALL the cheat sheets and some 5 minute subchapter about RF proximities...

**Comment by fabian-s** [comment]
e.g. landing page for https://noamross.github.io/gams-in-r-course/ seems more sensible than what we have now.

**Comment by berndbischl** [comment]
i think this is important, need to look into it, possibly connected with #6

**Comment by fabian-s** [comment]
@OmidCharrakh wrote: "egarding the landing page, I have created a test chapter that does the job. That is, chapter 0.1 is like a page that contains all its six sub-chapters (see the pic). However, I think this does not look good since we have lots of content in each sub-chapter, and putting all of them together on a single page makes it busy. BTW, if you think that we would better to convert all chapters in this way, I can do that easily."

I replied: 
I agree, somewhat, as far as it goes. I still think it's better than before.
Since the material has three levels of structure - chapters, subchapters and the different materials (slides, video, quiz/code) for each subchapter -- it seems natural to me that this is the way we should organize the website. 
the landing page should contain links to the different chapters, the chapters should contain links to pages for the different subchapters, each subchapter should get its own page with links to the next and previous subchapters as well as navigation elements that clearly show to the user "you are in subchapter XX.YY, this is how far along in the chapter XX you are, this is how you get back to the main page for chapter XX".

is a structure like that, with good navigation elements (sidebars, back- and forward buttons to jump to the next (sub-)chapter) possible in this framework?

**Comment by fabian-s** [comment]
ADDED for clarification: if you read my original comment, this is the structure I was suggesting. not *put all content for one chapter into one long list*

**Comment by OmidCharrakh** [comment]
Dear both, during the last week, I tried to resolve this issue. However, it seems that this problem can hardly be fixed. At least, we might need a professional programmer who can write some CSS and JS codes to design such landing pages. I searched in numerous Gatsby starter templates (see below), but none of them had such a pre-build feature. What should we do now?

1. https://supervised-ml-course.netlify.app/
2. https://noamross.github.io/gams-in-r-course/
3. https://intro-to-ds.netlify.app/
4. https://course.spacy.io/en/
5. https://nur1027.netlify.app/
6. https://gatsby-tutorial-starter.netlify.app/
7. https://gatsby.ghost.org/

**Comment by OmidCharrakh** [comment]
As explained above, this issue cannot be easily resolved. Hence, I close this issue for now. But, please let me know if you think we should discuss more.
