### ISSUE TITLE
modularization / pick-and-choose different chapters for different courses

### ISSUE THREAD

**Issue by fabian-s** [teaching-data-science/intro2ml#6]
(how) is it possible to build landing pages for courses that don't contain ALL the chapters we now have? 

E.g. if I want to build a 2-day course just on overfitting/tuning/resampling?

if that's feasible, this should go into CONTRIBUTING.md

(see also #5, which might be useful for controlling which content gets included on course-specific landing pages)

**Comment by berndbischl** [comment]
ńot sure i follow. you simply create the MD files manually? 
so you could copy the current I2ML webpage repo (omids new work) and edit the MD files so stuff disappears you don't like?

**Comment by fabian-s** [comment]
.... yeah, that works.

**Comment by berndbischl** [comment]
actually i wanna keep this open a bit.  
i remember a thing @ja-thomas said during the workshop:
we would have one MD-chunk per sub chapter. that makes it really easy to have remixes.
i think we already have that. but we should try this out at least once and document

**Comment by OmidCharrakh** [comment]
As I explained in issue #5, to have such a feature, we would probably need an advanced programmer. Hence, for now, I close this issue. BTW, please reopen this issue if you feel that we need to discuss further.
