### ISSUE TITLE
quizzes are still broken

### ISSUE THREAD

**Issue by fabian-s** [teaching-data-science/intro2ml#7]
.. i know you know, but, you know...
let's have an issue for that so we *keep on knowing* that.

2 ways forward: 

1 - figure out how to do real multiple choice  
2 - split each quiz into a series of TRUE/FALSE questions, one for each statement

**Comment by berndbischl** [comment]
is that the issue where each MC question can only have one true answer?

**Comment by fabian-s** [comment]
yes

**Comment by berndbischl** [comment]
ok, at leats omid looked into it, but couldn't find a (technical) way to solve this.
i told him to restructure the quizzes then. I am still ok with this, but maybe lets google a little bit more before we give up and partially throw away what we have

**Comment by berndbischl** [comment]
i mean we simply have to adapt this here. this is simple JS code

https://github.com/teaching-data-science/intro2ml/blob/master/src/components/choice.js

that MUST be doable

**Comment by schalkdaniel** [comment]
Quizzes should work with #23, please confirm. Preview is here: https://deploy-preview-23--introduction-to-machine-learning.netlify.app/

**Comment by schalkdaniel** [comment]
PR is now merged since there is no reply, reopen if any issues occur.
