### ISSUE TITLE
tag markup in chapters/*.md seems wrong

### ISSUE THREAD

**Issue by fabian-s** [teaching-data-science/intro2ml#9]
we have videos, slides, quizzes all declared as 
``` 
<exercise>
...
</exercise>
```

even though there seems to be (at least) a specific `<slides>`-tag (compare https://raw.githubusercontent.com/noamross/gams-in-r-course/master/chapters/chapter1.md)?

having  everything there is declared as an `<exercise>` seems very hacky and working against the structure of the framework...?

**Comment by OmidCharrakh** [comment]
Thanks, Fabian! There are basically two tags in this framework: `<exercise>` and `<slides>`. The latter can be used on websites that have .md slides. In our case, we have .pdf slides, and hence the only tag that we can use is `<exercise>`.
